name: any_logger_mysql
description: >-
  Store logs in MySQL with automatic table management, batching, rotation, and query API. Perfect for audit trails and log analysis.

version: 1.0.4

homepage: https://github.com/raoulsson/any_logger_mysql
repository: https://github.com/raoulsson/any_logger_mysql

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  any_logger: ^1.0.7
  mysql1: ^0.20.0

dev_dependencies:
  test: ^1.24.0

topics:
  - logging
  - mysql
  - database
  - audit
  - analytics

funding:
  - https://github.com/sponsors/raoulsson
  - https://www.buymeacoffee.com/raoulsson